### PR TITLE
Orgin

### PR DESCRIPTION
**Pull request by FAfacq3**
I think this is almost of work I done yet. if anyone have any question, just ask me. i will give a answer as soon as possible.

### CODE REVIEW

**Comment by Weetabicx** [comment]
I think the implementation of user and it's related features was supposed to by done by Harvey

**Comment by FAfacq3** [comment]
oh, that is a mistake, I fotgot to change it befor i push. you can delete it.

**Comment by FAfacq3** [comment]
don't close all for them!! there are some work contact to my other work. All right, I will give a version which don't have user login worked.

**Comment by Weetabicx** [comment]
I created a new PR which removed most of the user stuff, it breaks the code but it will let Harvey do his part

**Comment by FAfacq3** [comment]
thanks

**Pull request closed without merging**
